### PR TITLE
WIP: Feature/redirects

### PR DESCRIPTION
**Pull request by subhendukundu**
This contains a part of #124 This is my bad. If 124 is getting merged then I don't have to remove them but it doesn't, I will resolve it.

Can someone please review this and tell me what do you think?

### CODE REVIEW

**Comment by subhendukundu** [comment]
I need some suggestions on this one. Can anyone help?

**Comment by traffisco** [comment]
> I need some suggestions on this one. Can anyone help?

Probably better to just ask ;)

**Comment by subhendukundu** [comment]
We dont have node env here. So the way I am trying to do here is
1. Read the config file
2. Get the redirect data, create a json file in the worker file (As config file does `module.exports` where we are reading as `import` and this gonna throw error due to es and commonjs. Question on this one, can we make webpack to read it as well? if not any other alternative?
3. This is working so far. Now I will try to add regex and patterns. But does the approach looks good?

**Comment by subhendukundu** [comment]
@jplhomer how about this one? Am I heading in the right direction?

**Pull request merged**
