### PR TITLE
feat(cli): Keep looking in parent folder for webpack.client.config.js…

### LINKED ISSUE #88: Dev server cannot start in monorepo project
Hello!

I tried to setup Flareact in monorepo project, but `flareact dev` is always fail. From the error being printed, `webpack-dev-server `cannot resolve `node_modules/flareact/configs/webpack.client.config.js`.

My Flareact site is located on `/website`, while the real `node_modules` is located on `/`. But `webpack-dev-server` is lookin for the config on `/website/node_modules`.

Here are my environments:
- Node version: v14.15.3
- Package manager: Yarn v1.22.10
- OS: Ubuntu 20.04 on WSL2

Error message:
```
🚀 Starting Flareact dev server on http://localhost:8080 ...

[client] internal/modules/cjs/loader.js:883
[client]   throw err;
[client]   ^
[client] 
[client] Error: Cannot find module '/home/izznatsir/projects/github.com/izznatsir/radix-tw/website/node_modules/flareact/configs/webpack.client.config.js'
[client] Require stack:
[client] - /home/izznatsir/projects/github.com/izznatsir/radix-tw/node_modules/webpack-cli/bin/utils/convert-argv.js
[client] - /home/izznatsir/projects/github.com/izznatsir/radix-tw/node_modules/webpack-dev-server/bin/webpack-dev-server.js
[client]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[client]     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
[client]     at Module.require (internal/modules/cjs/loader.js:952:19)
[client]     at require (internal/modules/cjs/helpers.js:88:18)
[client]     at WEBPACK_OPTIONS (/home/izznatsir/projects/github.com/izznatsir/radix-tw/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
[client]     at requireConfig (/home/izznatsir/projects/github.com/izznatsir/radix-tw/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
[client]     at /home/izznatsir/projects/github.com/izznatsir/radix-tw/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
[client]     at Array.forEach (<anonymous>)
[client]     at module.exports (/home/izznatsir/projects/github.com/izznatsir/radix-tw/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
[client]     at Object.<anonymous> (/home/izznatsir/projects/github.com/izznatsir/radix-tw/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40) {
[client]   code: 'MODULE_NOT_FOUND',
[client]   requireStack: [
[client]     '/home/izznatsir/projects/github.com/izznatsir/radix-tw/node_modules/webpack-cli/bin/utils/convert-argv.js',
[client]     '/home/izznatsir/projects/github.com/izznatsir/radix-tw/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
[client]   ]
[client] }
[client] webpack-dev-server --config node_modules/flareact/configs/webpack.client.config.js --mode development exited with code 1
```

### PR DESCRIPTION
**Pull request by izznatsir**
… if not found.

Fixes #88

This feature is to fix flareact command in monorepo project, where all dependencies are aggregated in root folder node_modules. So we need to find the config file in parent folder.

TODOS:
- [x] Manual testing

### CODE REVIEW

**Review by jplhomer — CHANGES_REQUESTED** [review]
Thanks for this! A couple things I'd love to see:

- Let's set `rootPath + webpackConfigPath` as a top-level variable after the `while` loop as e.g. `resolvedWebpackConfigPath` to reduce repetition
- Could we add a system to prevent infinite loops, using e.g. `attempts++` and `maxAttempts = 2` or something? If max attempts have been exhausted, `console.error` and `process.exit(1)`.

**Comment by izznatsir** [comment]
> * Let's set `rootPath + webpackConfigPath` as a top-level variable after the `while` loop as e.g. `resolvedWebpackConfigPath` to reduce repetition

What if we reassign webpackConfigPath with the resolved path after the while loop?

> * Could we add a system to prevent infinite loops, using e.g. `attempts++` and `maxAttempts = 2` or something? If max attempts have been exhausted, `console.error` and `process.exit(1)`.

Sure, if the limit is reached should I just throw an error?

**Comment by jplhomer** [comment]
Whichever method is cleanest!

Yep - if the limit is reached, `console.error` an error and then `process.exit(1)`.

**Comment by izznatsir** [comment]
Changes has been made as you have requested.
Thanks for your guidance!

**Comment by jplhomer** [comment]
❤️

**Review by jplhomer — APPROVED** [review]

**Pull request merged**
