### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by christian-schab**
Added typescript as discussed in #20 

**Details**

- Added @babel/preset-typescript  for converting typescript files to js.
- Added jsx, ts and tsx as allowed file suffixes for pages
- Added a short test
- Added jsx, ts and tsx for module resolve in webpack config

### CODE REVIEW

**Comment by christian-schab** [comment]
Necessary modifications on flareact-template to make this work are here:
https://github.com/flareact/flareact-template/pull/1

**Comment by jplhomer** [comment]
@christian-schab This is so great - thank you for taking this on! 🎉 

I'm doing testing locally and working to wrap my brain around everything here.

In the meantime, would you be able to add an example in the `examples/with-typescript` directory of this repo? I noticed you added one here https://github.com/flareact/flareact-template/pull/1 but I think it would be better suited in this repo.

**Comment by christian-schab** [comment]
@jplhomer I've added an example "with-typescript" based on your example "with-cms-wordpress".

It is deployed here: https://flareact-with-typescript.web-academy.workers.dev/

**But**: There is still an issue with page loading on clicking a link with a dynamic path.
https://flareact-with-typescript.web-academy.workers.dev/posts/post-193 works fine if you go straight to the url.
But if you click a "Post XXX" link on the index page it fails.

In dev mode it tries to load "http://localhost:8080/pages/posts/post-193.js".
In production mode it fails with a "TypeError: Cannot read property 'forEach' of undefined"
caused by "getDependencies" in page-loader.js returning undefined.

I try to solve this but any thoughts are highly appreciated.

**Comment by cj** [comment]
@christian-schab @jplhomer here's a gist to get you up and running quickly with typescript using https://github.com/ds300/patch-package https://gist.github.com/cj/032339b740709b8566792b4459905eda

Thank you @christian-schab for the inspiration!

**Comment by jplhomer** [comment]
@christian-schab Thanks again for this!

- Going to merge this into an `alpha` release so we can keep experimenting with it before it hits canary/latest.
- I took out your example for now. I will open a new branch/PR to keep iterating on it, as I'd love to see a simple version reflecting [Next's version](https://github.com/vercel/next.js/tree/canary/examples/with-typescript/)

🎉 🚀

**Pull request merged**
