### PR TITLE
Flareact powered 404 page

### PR DESCRIPTION
**Pull request by traffisco**
To create a custom React powered 404 page you can create a `pages/404.js` file.

```
// pages/404.js
export async function getEdgeProps({ params }) {
    const { originalPath } = params;
    const data = await someFallbackDataRequest();
    
    return {
        props: {
            originalPath,
            data,
        },
        notFound: true, // send 404 header
        revalidate: 60, // Revalidate your data once every 60 seconds
    }
}

export default function Index({ originalPath, data }) {
    return (
        <div>
          <h1>{originalPath} - 404 Not Found </h1>
          <ul>
            {data.map((item) => {
              return <li key={item.id}>...</li>;
            })}
          </ul>
        </div>
    )
}
```

### CODE REVIEW

**Comment by tj-kev** [comment]
Great!

**Comment by tj-kev** [comment]
@traffisco I think I may have spotted an issue. With this enabled when trying to load assets from the public folder they are returning 404.

**Comment by traffisco** [comment]
> @traffisco I think I may have spotted an issue. With this enabled when trying to load assets from the public folder they are returning 404.

Hmm...
will check again soonish. Whisky time

**Comment by traffisco** [comment]
@tj-kev fixed with #218

**Pull request merged**
